# Manipulación de datos con pandas.
* [Curso udemy](https://www.udemy.com/course/data-manipulation-in-python)
* [Dataset heart disease uci](https://www.kaggle.com/datasets/mragpavank/heart-diseaseuci)

El dataset original del cuso no lo encontre, pero usare este dataset.

## Importando librerias

In [1]:
import pandas as pd
import numpy as np

## Leer csv para crear un dataframe

In [3]:
filename = "heart.csv"
dfheart = pd.read_csv(filename)
dfheart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

## Leer csv con numpy

In [5]:
data = np.loadtxt(filename, delimiter=",", skiprows=1)
print(data)

[[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]
