# Pandas vs Numpy

In [42]:
import pandas as pd
import numpy as np

df = pd.read_csv("heart.csv")

## Convirtiendo dataframe a numpy.

Para hacer la conversion usamos el to_numpy del objeto df

In [43]:
data = df.to_numpy()

Esto nos dara como resultado...

In [44]:
data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

Para ver una muestra del dataframe junto al nombre de sus columnas, usamos en el metodo .head()

In [45]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Ahora si queremos ver que tipo de datos esta guardado en el dataframe, lo podemos hacer de la siguiente forma.

In [46]:
print(data.dtype, data)

float64 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


Como podemos ver en la salida nos indica que los datos son de tipo flotante.

In [47]:
data[0,0] = 100
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Nuestro siguiente ejercicio sera crear un segundo dataframe apartir del primero, usando las columnas age, sex y cp

In [48]:
df2 = df[["age","sex","cp"]]

Una vez creado nuestro nuevo dataframe lo transformaremos en un array numpy.

In [49]:
data_view = df2.to_numpy()

Vamos a crear una copia del array usando el to_numpy(copy=True)

Finalizado este proceso procedemos a asignarle el numero cien a la coordenada 0, 0.

In [50]:
data_view[0,0] = 100

Verificamos nuestro resultado.

In [51]:
df2.head()

age  sex  cp
0  100    1   3
1   37    1   2
2   41    0   1
3   56    1   1
4   57    0   0

Modificar el dataframe original df

In [52]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [53]:
df.age.to_numpy()[0] = 100
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0  100    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Ahora vamos a ver como obtener la media de las edades.

In [54]:
print(df['age'].mean(), df['age'].to_numpy().mean())

54.48844884488449 54.48844884488449


Ahora vamos a calcular el cuantil, pasandole como parametro el percentil 0.5 y nos dara el segundo cuartil.

In [55]:
print(df['age'].quantile(0.5))

55.0


Ahora haremos lo mismo pero transformando el dataframe a un array numpy

In [57]:
print(np.quantile(df['age'].to_numpy(), 0.5))

55.0


Vamos a cambiar la forma de nuestro array sin alterar los datos usando el comando reshape

In [60]:
print(np.reshape(df['age'], (3,-1)))

[[100  37  41  56  57  57  56  44  52  57  54  48  49  64  58  50  58  66
   43  69  59  44  42  61  40  71  59  51  65  53  41  65  44  54  51  46
   54  54  65  65  51  48  45  53  39  52  44  47  53  53  51  66  62  44
   63  52  48  45  34  57  71  54  52  41  58  35  51  45  44  62  54  51
   29  51  43  55  51  59  52  58  41  45  60  52  42  67  68  46  54  58
   48  57  52  54  45  53  62  52  43  53  42]
 [ 59  63  42  50  68  69  45  50  50  64  57  64  43  55  37  41  56  46
   46  64  59  41  54  39  34  47  67  52  74  54  49  42  41  41  49  60
   62  57  64  51  43  42  67  76  70  44  60  44  42  66  71  64  66  39
   58  47  35  58  56  56  55  41  38  38  67  67  62  63  53  56  48  58
   58  60  40  60  64  43  57  55  65  61  58  50  44  60  54  50  41  51
   58  54  60  60  59  46  67  62  65  44  60]
 [ 58  68  62  52  59  60  49  59  57  61  39  61  56  43  62  63  65  48
   63  55  65  56  54  70  62  35  59  64  47  57  55  64  70  51  58  60
   77  35  70  59 