# Pandas vs Numpy

In [42]:
import pandas as pd
import numpy as np

df = pd.read_csv("heart.csv")

## Convirtiendo dataframe a numpy.

Para hacer la conversion usamos el to_numpy del objeto df

In [43]:
data = df.to_numpy()

Esto nos dara como resultado...

In [44]:
data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

Para ver una muestra del dataframe junto al nombre de sus columnas, usamos en el metodo .head()

In [45]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Ahora si queremos ver que tipo de datos esta guardado en el dataframe, lo podemos hacer de la siguiente forma.

In [46]:
print(data.dtype, data)

float64 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


Como podemos ver en la salida nos indica que los datos son de tipo flotante.

In [47]:
data[0,0] = 100
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Nuestro siguiente ejercicio sera crear un segundo dataframe apartir del primero, usando las columnas age, sex y cp

In [48]:
df2 = df[["age","sex","cp"]]

Una vez creado nuestro nuevo dataframe lo transformaremos en un array numpy.

In [49]:
data_view = df2.to_numpy()

Vamos a crear una copia del array usando el to_numpy(copy=True)

Finalizado este proceso procedemos a asignarle el numero cien a la coordenada 0, 0.

In [50]:
data_view[0,0] = 100

Verificamos nuestro resultado.

In [51]:
df2.head()

age  sex  cp
0  100    1   3
1   37    1   2
2   41    0   1
3   56    1   1
4   57    0   0

Modificar el dataframe original df

In [52]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [53]:
df.age.to_numpy()[0] = 100
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0  100    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Ahora vamos a ver como obtener la media de las edades.

In [54]:
print(df['age'].mean(), df['age'].to_numpy().mean())

54.48844884488449 54.48844884488449


Ahora vamos a calcular el cuantil, pasandole como parametro el percentil 0.5 y nos dara el segundo cuartil.

In [55]:
print(df['age'].quantile(0.5))

55.0


Ahora haremos lo mismo pero transformando el dataframe a un array numpy

In [57]:
print(np.quantile(df['age'].to_numpy(), 0.5))

55.0


Vamos a cambiar la forma de nuestro array sin alterar los datos usando el comando reshape

In [ ]:
print(np.reshape(df['age'], (3,-1)))

TypeError: reshape() missing 1 required positional argument: 'newshape'